export const QUERY_KEYS = {
  kingdoms_key: "kingdoms",
  children_key: "children",
  specie_key: "specie",
  parents_key: "parents",
  user_db_key: "user_db",
  daily_challenge_key: "daily_challenge",
  challenge_tips_key: "challenge_tips",
  vernacular_names_key: "vernacular_names",
  user_seen_species_key: "user_seen_species",
  user_activities_key: "user_activities",
  species_cache_key: "species-cache",
  user_achievements_key: "user_achievements",
  user_challenge_history_key: "user_challenge_history",
  specie_gallery_key: "specie_gallery",
  achievement_progress_key: "achievement_progress",
  seen_specie_by_key_key: "seen_specie_by_key",
  favorite_species_page_key: "favorite_species_page",
  user_lists_key: "user_lists",
  user_liked_lists_key: "user_liked_lists",
  public_lists_key: "public_lists",
  list_detail_key: "list_detail",
  list_species_key: "list_species",
  my_lists_picker_key: "my_lists_picker",
  lists_with_species_key: "lists_with_species",
  public_profile_key: "public_profile",
};
