export const QUERY_KEYS = {
  kingdoms_key: "kingdoms",
  children_key: "children",
  specie_key: "specie",
  parents_key: "parents",
  user_db_key: "user_db",
  daily_challenge_key: "daily_challenge",
  challenge_tips_key: "challenge_tips",
  vernacular_names_key: "vernacular_names",
  user_seen_species_key: "user_seen_species",
  user_activities_key: "user_activities",
  species_cache_key: "species-cache",
  user_achievements_key: "user_achievements",
  user_challenge_history_key: "user_challenge_history",
};
