import {
  Award,
  Trophy,
  Target,
  Images,
  Zap,
  Leaf,
  Crown,
  Star,
  Shield,
  Flame,
} from "lucide-react";

export const userProgress = {
  memberSince: "Agosto 2025",
  totalSpecies: 127,
  correctAnswers: 89,
  streak: 12,
  medals: 8,
  challenges: 23,
  rank: 2,
  totalUsers: 1250,
  accuracy: 87,
  pointsToNextRank: 340,
};

export const userAchievements = {
  unlocked: [
    {
      id: 1,
      name: "Caçador de Dragões",
      icon: Award,
      description: "Descobriu mais de 10 espécies com o nome 'dragão'",
    },
    {
      id: 2,
      name: "Estudante Consistente",
      icon: Flame,
      description: "10 dias consecutivos de estudo",
    },
    {
      id: 3,
      name: "Primeiro Passo",
      icon: Star,
      description: "Primeira espécie descoberta",
    },
    {
      id: 4,
      name: "Mamífero Expert",
      icon: Crown,
      description: "Explorou 50 mamíferos diferentes",
    },
    {
      id: 5,
      name: "Desafiador",
      icon: Target,
      description: "Completou 20 desafios",
    },
    {
      id: 6,
      name: "Precisão",
      icon: Shield,
      description: "85% de acerto em desafios",
    },
  ],
  locked: [
    {
      id: 7,
      name: "Velocista",
      icon: Zap,
      description: "5 desafios em menos de 30s cada",
      progress: 60,
    },
    {
      id: 8,
      name: "Colecionador",
      icon: Images,
      description: "Descobrir 500 espécies",
      progress: 25,
    },
    {
      id: 9,
      name: "Maratonista",
      icon: Flame,
      description: "30 dias consecutivos",
      progress: 40,
    },
    {
      id: 10,
      name: "Ave Expert",
      icon: Leaf,
      description: "Explorar 100 aves",
      progress: 15,
    },
    {
      id: 11,
      name: "Mestre Taxonomia",
      icon: Crown,
      description: "Completar todos os reinos",
      progress: 8,
    },
    {
      id: 12,
      name: "Lenda",
      icon: Trophy,
      description: "Top 10 no ranking global",
      progress: 0,
    },
    {
      id: 17,
      name: "Velocista",
      icon: Zap,
      description: "5 desafios em menos de 30s cada",
      progress: 60,
    },
    {
      id: 18,
      name: "Colecionador",
      icon: Images,
      description: "Descobrir 500 espécies",
      progress: 25,
    },
    {
      id: 19,
      name: "Maratonista",
      icon: Flame,
      description: "30 dias consecutivos",
      progress: 40,
    },
    {
      id: 110,
      name: "Ave Expert",
      icon: Leaf,
      description: "Explorar 100 aves",
      progress: 15,
    },
    {
      id: 111,
      name: "Mestre Taxonomia",
      icon: Crown,
      description: "Completar todos os reinos",
      progress: 8,
    },
    {
      id: 112,
      name: "Lenda",
      icon: Trophy,
      description: "Top 10 no ranking global",
      progress: 0,
    },
    {
      id: 27,
      name: "Velocista",
      icon: Zap,
      description: "5 desafios em menos de 30s cada",
      progress: 60,
    },
    {
      id: 28,
      name: "Colecionador",
      icon: Images,
      description: "Descobrir 500 espécies",
      progress: 25,
    },
    {
      id: 29,
      name: "Maratonista",
      icon: Flame,
      description: "30 dias consecutivos",
      progress: 40,
    },
    {
      id: 210,
      name: "Ave Expert",
      icon: Leaf,
      description: "Explorar 100 aves",
      progress: 15,
    },
    {
      id: 211,
      name: "Mestre Taxonomia",
      icon: Crown,
      description: "Completar todos os reinos",
      progress: 8,
    },
    {
      id: 212,
      name: "Lenda",
      icon: Trophy,
      description: "Top 10 no ranking global",
      progress: 0,
    },
    {
      id: 217,
      name: "Velocista",
      icon: Zap,
      description: "5 desafios em menos de 30s cada",
      progress: 60,
    },
    {
      id: 218,
      name: "Colecionador",
      icon: Images,
      description: "Descobrir 500 espécies",
      progress: 25,
    },
    {
      id: 219,
      name: "Maratonista",
      icon: Flame,
      description: "30 dias consecutivos",
      progress: 40,
    },
    {
      id: 2110,
      name: "Ave Expert",
      icon: Leaf,
      description: "Explorar 100 aves",
      progress: 15,
    },
    {
      id: 2111,
      name: "Mestre Taxonomia",
      icon: Crown,
      description: "Completar todos os reinos",
      progress: 8,
    },
    {
      id: 2112,
      name: "Lenda",
      icon: Trophy,
      description: "Top 10 no ranking global",
      progress: 0,
    },
  ],
};
